### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by adator85**
Avoid this Undefined property error.

Warning: Undefined property: stdClass::$geoip in /var/www/unrealircd-webpanel/plugins/IPCloneDetectorAndASNAnalyzer/index.php on line 363

### CODE REVIEW

**Comment by Madriix** [comment]
Hi @adator85 If you have this error, it means you haven’t enabled GeoIP in your modules.conf configuration for UnrealIRCd. There are many people who forget to update modules.conf as soon as they update their UnrealIRCd, including me.

**Comment by adator85** [comment]
Hi @Madriix, no the goeip module was activated. i think the issue is coming from the 127.0.0.1 ip's

however even if the module is not activated the plugin should show a controlled error message.

**Comment by ValwareIRC** [comment]
Indeed, not everyone has GEOIP @Madriix, @adator85 is correct. Permission to merge?

**Comment by ValwareIRC** [comment]
So yeah, as much as I agree with you here @adator85, I can't unfortunately accept pull requests for other people's plugins. I would have to ask that you make a Pull Request to his fork of this repository, and you can make edit suggestions there, and after it's been accepted, then @Madriix can send a Pull Request to this repository.
I do agree with you though, and I wonder if it's been patched yet.

**Pull request closed without merging**
